version: "3.8"

services:
  bot:
    image: ghcr.io/tancred423/paissa-house-discord-bot:latest
    container_name: paissa-house-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REGISTER_COMMANDS=false
      - DEPLOYMENT_HASH=${DEPLOYMENT_HASH:-}
    volumes:
      - ./db_volume:/app/data

  register-commands:
    image: ghcr.io/tancred423/paissa-house-discord-bot:latest
    env_file:
      - .env
    environment:
      - REGISTER_COMMANDS=true
      - DEPLOYMENT_HASH=${DEPLOYMENT_HASH:-}
    restart: "no"

# Using host-mounted volume instead of named volume
