services:
  bot:
    image: ghcr.io/tancred423/paissa-house-discord-bot:latest
    container_name: paissa-house-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REGISTER_COMMANDS=false

  register-commands:
    image: ghcr.io/tancred423/paissa-house-discord-bot:latest
    env_file:
      - .env
    environment:
      - REGISTER_COMMANDS=true
    restart: "no"
