services:
  bot:
    image: paissa-house-discord-bot-dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paissa-house-bot-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REGISTER_COMMANDS=false
      - DEPLOYMENT_HASH=${DEPLOYMENT_HASH:-dev}
      - ENVIRONMENT=development
    volumes:
      - paissa_data:/app/data
      - ./src:/app/src

volumes:
  paissa_data:
    name: paissa_data_dev
