import { WorldData } from "../types/WorldData.ts";

const WORLDS: WorldData[] = [
  { id: 404, name: "Marilith", datacenter_id: 11, datacenter_name: "Dynamis" },
  { id: 21, name: "Ravana", datacenter_id: 9, datacenter_name: "Materia" },
  { id: 22, name: "Bismarck", datacenter_id: 9, datacenter_name: "Materia" },
  { id: 23, name: "Asura", datacenter_id: 3, datacenter_name: "Mana" },
  { id: 405, name: "Seraph", datacenter_id: 11, datacenter_name: "Dynamis" },
  { id: 28, name: "Pandaemonium", datacenter_id: 3, datacenter_name: "Mana" },
  {
    id: 406,
    name: "Halicarnassus",
    datacenter_id: 11,
    datacenter_name: "Dynamis",
  },
  { id: 407, name: "Maduin", datacenter_id: 11, datacenter_name: "Dynamis" },
  { id: 33, name: "Twintania", datacenter_id: 7, datacenter_name: "Light" },
  { id: 34, name: "Brynhildr", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 35, name: "Famfrit", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 36, name: "Lich", datacenter_id: 7, datacenter_name: "Light" },
  { id: 37, name: "Mateus", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 39, name: "Omega", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 40, name: "Jenova", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 41, name: "Zalera", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 42, name: "Zodiark", datacenter_id: 7, datacenter_name: "Light" },
  { id: 43, name: "Alexander", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 44, name: "Anima", datacenter_id: 3, datacenter_name: "Mana" },
  { id: 45, name: "Carbuncle", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 46, name: "Fenrir", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 47, name: "Hades", datacenter_id: 3, datacenter_name: "Mana" },
  { id: 48, name: "Ixion", datacenter_id: 3, datacenter_name: "Mana" },
  { id: 49, name: "Kujata", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 50, name: "Typhon", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 51, name: "Ultima", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 53, name: "Exodus", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 54, name: "Faerie", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 55, name: "Lamia", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 56, name: "Phoenix", datacenter_id: 7, datacenter_name: "Light" },
  { id: 57, name: "Siren", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 58, name: "Garuda", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 59, name: "Ifrit", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 61, name: "Titan", datacenter_id: 3, datacenter_name: "Mana" },
  { id: 62, name: "Diabolos", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 63, name: "Gilgamesh", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 64, name: "Leviathan", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 65, name: "Midgardsormr", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 66, name: "Odin", datacenter_id: 7, datacenter_name: "Light" },
  { id: 67, name: "Shiva", datacenter_id: 7, datacenter_name: "Light" },
  { id: 68, name: "Atomos", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 69, name: "Bahamut", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 70, name: "Chocobo", datacenter_id: 3, datacenter_name: "Mana" },
  { id: 71, name: "Moogle", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 72, name: "Tonberry", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 73, name: "Adamantoise", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 74, name: "Coeurl", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 75, name: "Malboro", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 76, name: "Tiamat", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 77, name: "Ultros", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 78, name: "Behemoth", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 79, name: "Cactuar", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 80, name: "Cerberus", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 81, name: "Goblin", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 83, name: "Louisoix", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 85, name: "Spriggan", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 86, name: "Sephirot", datacenter_id: 9, datacenter_name: "Materia" },
  { id: 87, name: "Sophia", datacenter_id: 9, datacenter_name: "Materia" },
  { id: 88, name: "Zurvan", datacenter_id: 9, datacenter_name: "Materia" },
  { id: 90, name: "Aegis", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 91, name: "Balmung", datacenter_id: 8, datacenter_name: "Crystal" },
  { id: 92, name: "Durandal", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 93, name: "Excalibur", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 94, name: "Gungnir", datacenter_id: 1, datacenter_name: "Elemental" },
  { id: 95, name: "Hyperion", datacenter_id: 5, datacenter_name: "Primal" },
  { id: 96, name: "Masamune", datacenter_id: 3, datacenter_name: "Mana" },
  { id: 97, name: "Ragnarok", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 98, name: "Ridill", datacenter_id: 2, datacenter_name: "Gaia" },
  { id: 99, name: "Sargatanas", datacenter_id: 4, datacenter_name: "Aether" },
  { id: 24, name: "Belias", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 29, name: "Shinryu", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 30, name: "Unicorn", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 31, name: "Yojimbo", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 32, name: "Zeromus", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 52, name: "Valefor", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 60, name: "Ramuh", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 82, name: "Mandragora", datacenter_id: 10, datacenter_name: "Meteor" },
  { id: 400, name: "Sagittarius", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 401, name: "Phantom", datacenter_id: 6, datacenter_name: "Chaos" },
  { id: 402, name: "Alpha", datacenter_id: 7, datacenter_name: "Light" },
  { id: 403, name: "Raiden", datacenter_id: 7, datacenter_name: "Light" },
  {
    id: 408,
    name: "Cuchulainn",
    datacenter_id: 11,
    datacenter_name: "Dynamis",
  },
  { id: 409, name: "Kraken", datacenter_id: 11, datacenter_name: "Dynamis" },
  { id: 410, name: "Rafflesia", datacenter_id: 11, datacenter_name: "Dynamis" },
  { id: 411, name: "Golem", datacenter_id: 11, datacenter_name: "Dynamis" },
];

export class WorldDataHelper {
  static getDatacenters(): string[] {
    const datacenters = new Set(WORLDS.map((world) => world.datacenter_name));
    return Array.from(datacenters).sort();
  }

  static getWorldsByDatacenter(datacenterName: string): WorldData[] {
    return WORLDS.filter((world) => world.datacenter_name === datacenterName);
  }
}
