name: Deploy Discord Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.3

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
          tags: |
            ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:latest
            ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:buildcache,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/paissa-bot

            # Create db_volume directory if it doesn't exist
            echo "Setting up database directory..."
            mkdir -p db_volume
            chmod -R 777 db_volume

            # Backup database if it exists
            if [ -f db_volume/paissa_bot.db ]; then
              echo "Creating database backup..."
              cp db_volume/paissa_bot.db db_volume/paissa_bot.db.bak.$(date +%Y%m%d%H%M%S)
              echo "Database backup created"
            else
              echo "No existing database file found"
            fi

            # Display volume directory contents
            echo "Current db_volume contents:"
            ls -la db_volume

            # Stop and remove only the bot's containers
            docker-compose down

            # Clean up any related dangling images without affecting other services
            docker image prune -f --filter "label=org.opencontainers.image.source=https://github.com/${{ vars.USERNAME_LOWERCASE }}/FFXIV_PaissaHouseDiscordBot"

            # Pull the latest images
            docker-compose pull

            # Register application commands (production mode for global commands)
            DEPLOYMENT_HASH=${{ github.sha }} docker-compose run -e ENVIRONMENT=production register-commands

            # Start the containers with deployment hash for transparency
            DEPLOYMENT_HASH=${{ github.sha }} docker-compose up -d bot

            # Show container info and check volumes
            echo "Container info:"
            docker inspect paissa-house-bot | grep -A 10 "Mounts"

            # Wait a bit for container to start up
            sleep 5

            # Check volume contents
            echo "Volume directory contents after deployment:"
            ls -la db_volume

            # Show logs to check for database errors
            echo "Container logs (database related):"
            docker logs paissa-house-bot | grep -i "database\|db\|data dir\|system"

            # Verify mounts are correct
            echo "Checking container mounts:"
            docker inspect paissa-house-bot --format '{{ .Mounts }}'

            # Wait a bit more for database to be created if it doesn't exist yet
            sleep 5
            echo "Final check of database file:"
            ls -la db_volume/paissa_bot.db || echo "WARNING: Database file still not found"
