name: Deploy Discord Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.3

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
          tags: |
            ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:latest
            ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ vars.USERNAME_LOWERCASE }}/paissa-house-discord-bot:buildcache,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/paissa-bot

            # Important: Backup the database before doing anything else
            mkdir -p data_backup
            if [ -f "data/paissa_bot.db" ]; then
              cp data/paissa_bot.db data_backup/
              echo "Database backup created"
            else
              echo "No database file found to backup"
            fi

            # Ensure data directory exists with correct permissions
            mkdir -p data
            chmod 755 data

            # Stop the containers but keep volumes
            docker-compose down

            # Clean up any related dangling images without affecting other services
            docker image prune -f --filter "label=org.opencontainers.image.source=https://github.com/${{ vars.USERNAME_LOWERCASE }}/FFXIV_PaissaHouseDiscordBot"

            # Pull the latest images
            docker-compose pull

            # Restore database if needed
            if [ -f "data_backup/paissa_bot.db" ] && [ ! -f "data/paissa_bot.db" ]; then
              cp data_backup/paissa_bot.db data/
              echo "Database restored from backup"
            fi

            # Start the containers with deployment hash for transparency
            DEPLOYMENT_HASH=${{ github.sha }} docker-compose up -d

            # Register commands after the main container is running
            # sleep 5
            # DEPLOYMENT_HASH=${{ github.sha }} docker-compose run --rm -e ENVIRONMENT=production register-commands
